### ISSUE TITLE
Q: Can RTF be used to model projector + lenses

### ISSUE THREAD

**Issue by kontramind** [ISET/isetrtf#1]
Dear,

First of all let me congratulate on the important work you have done and the published paper.

I have a question. 
I'm interested into using PBRT to simulate projector with lenses.
Please can you tell if ray-transfer function mechanism could be used?
And the ways how PBRT should be changed in order to achieve this.
Projector light in the PBRT are point-type sources.

Many thanks,
Aleksdndar

**Comment by wandell** [comment]
Thanks - that's an interesting question.  We are thinking a lot about light sources as well, but mostly head lights for cars.

Thomas Goossens is away this week.  When he returns, all of us will discuss your question and then get back to you if we have anything reasonably useful to add that might be helpful.

**Comment by kontramind** [comment]
@wandell , @tgoossens 

Many thanks for considering my question. I'm looking forward to eventual help on this matter.
Having lenses + projector would enable research in the area of structured light based acquisition systems.

BR
Aleksandar

**Comment by kontramind** [comment]
@wandell @tgoossens 

An additional thought... 
Projector light in PBRT is implemented as point type. But the lenses could bring focusing capabilities to other types of light source, e.g., AreaLight. This may have a positive effect in cases where one is to use projector on specular/transparent objects.

**Comment by tgoossens** [comment]
Dear @kontramind ,

Thank you for your message. Could you clarify what you are trying to simulate when you say "projector".
Maybe you can describe a specific example/use case.

Any system that could be simulated in PBRT if you would have full knowledge of the design can, in principle, also be simulated using a ray transfer function. This is because the RTF simply replaces any proprietary component  in your simulation.

All the best,

Thomas

**Comment by kontramind** [comment]
Dear @tgoossens ,

Many thanks for getting back to me.

I want to simulate a projector light source that can be used for experimentation with [structured light scanners](https://opg.optica.org/aop/fulltext.cfm?uri=aop-3-2-128&id=211561).

I can do simple experiments by means of projection light source that is already available in PBRT.
To do more close to real-life simulations, an implementation of projection light + lenses or maybe even area light + lenses would be even more useful. 

Would this be possible with RTF even though none of the light sources in PBRT, in contrast to the realistic camera, do not support lenses?

Kind regards,
Aleksandar

**Comment by tgoossens** [comment]
Dear Aleksandar,

Interesting. That is, for me, a new use case.
This would require to place lens elements a scene objects. This is possible in principle of course if you know the lens elements.
The RTF could of course also be used for this because it is simply a mathematical description of the input/output relation.

Somehow you need to fool PBRT : when a ray arrives somewher eyou need to produce a new ray.   My first guess would be to look at implementing a custom Bidirectional scattering distribution function. Maybe a ray arriving at such an RTF surface can be forced to be (specularly) scattered in a direction predicted by the polynomials?


Thomas

**Comment by tgoossens** [comment]
Closing this issue. Feel free to reach out via email again!
